# Generated by Django 4.1.1 on 2023-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'python'), ('js', 'JavaScript'), ('cpp', 'C++')], max_length=30),
        ),
    ]
